name: BridgingAnalyzer
main: ldcr.BridgingAnalyzer.BridgingAnalyzer
version: 1.0.0
author: Ldcr
softdepend: ["BridgingSkin"]
depend: ["LdcrUtils"]
commands:
  bridge:
    description: Bridging Analyzer Config
    usage: /bridge
  clearblock:
    description: clear placed block
    usage: /clearblock
  imstuck:
    description: destroy near block
    usage: /imstuck
  genvillager:
    description: create villager spawn point
    usage: /genvillager
permissions:
  bridginganalyzer.noclear:
    default: op
